[tool.poetry]
name = "scikit-mpe"
version = "0.1.0"
description = "Minimal path extraction using the fast marching method"
authors = ["Eugene Prilepin <esp.home@gmail.com>"]
license = "MIT"
readme = "README.md"
keywords = ["mpe", "fmm", "minimal-path", "fast-marching", "fast-marching-method"]

classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Image Processing",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Software Development :: Libraries",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: Implementation :: CPython",
]

repository = "https://github.com/espdev/mpe"

[tool.poetry.dependencies]
python = "^3.6"
numpy = "^1.18.1"
scipy = "^1.4.1"
scikit-fmm = "^2019.1.30"
pydantic = "^1.4"

[tool.poetry.dev-dependencies]
pytest = "^5.3.5"
pytest-benchmark = "^3.2.3"
coverage = "^5.0.3"
matplotlib = "^3.1.3"
scikit-image = "^0.16.2"
sphinx = "^2.3.1"
numpydoc = "^0.9.2"
toml = "^0.10.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
